# This tells the scanner: "Send the results to the Cloud, not Localhost"
sonar.host.url=https://sonarcloud.io

# Uniquely identifies your project on SonarCloud
# You get these from the project Information page on SonarCloud
sonar.organization=pwurbs
sonar.projectKey=wuflow

# Source code location. 
# "." means "everything in this directory"
# we exclude some files and folders later
sonar.sources=.

# Exclusions (Optional)
# Don't scan build results, database files
sonar.exclusions=bin/**,*.db*

# Specify test files
sonar.tests=.
sonar.test.inclusions=**/*_test.go,static/js/tests/**/*.test.js,playwright/**/*.spec.ts

# Test coverage report
sonar.go.coverage.reportPaths=coverage.out
sonar.javascript.lcov.reportPaths=static/js/coverage/lcov.info
sonar.coverage.inclusions=backend/**/*.go,static/js/*.js,static/js/components/*.js
# the inclusion is not sufficient to exclude static files, so we need to exclude them explicitly
sonar.coverage.exclusions=static/**/*.css,\\\
                          static/**/*.html,\\\
                          static/js/tests/**,\\\
                          static/js/node_modules/**,\\\
                          main.go,\\\
                          playwright/**,\\\
                          static/js/api.js,\\\
                          static/js/app.js,\\\
                          static/js/drag.js,\\\
                          static/js/vitest.config.js,\\\
                          static/js/components/backlog.js,\\\
                          static/js/components/card.js,\\\
                          static/js/components/deadlines.js,\\\
                          static/js/components/labelFilter.js,\\\
                          static/js/components/planning.js,\\\
                          static/js/components/priorityFilter.js,\\\
                          static/js/components/setup.js
