# This tells the scanner: "Send the results to the Cloud, not Localhost"
sonar.host.url=https://sonarcloud.io

# Uniquely identifies your project on SonarCloud
# You get these from the project Information page on SonarCloud
sonar.organization=pwurbs-oss
sonar.projectKey=wuflow-oss

# Source code location. 
# "." means "everything in this directory"
# we exclude some files and folders later
sonar.sources=.

# Exclusions (Optional)
# Don't scan build results, database files
sonar.exclusions=bin/**,*.db*,docs/screenshots/**

# Specify test files
sonar.tests=.
sonar.test.inclusions=**/*_test.go,static/js/tests/**/*.test.js,playwright/**/*.spec.ts,scripts/**/*.mjs

# Test coverage report
sonar.go.coverage.reportPaths=backend/test-results/coverage.out
sonar.javascript.lcov.reportPaths=static/js/coverage/lcov.info
sonar.coverage.inclusions=backend/**/*.go,static/js/*.js,static/js/components/*.js
# the inclusion is not sufficient to exclude static files, so we need to exclude them explicitly
sonar.coverage.exclusions=static/**/*.css,\\\
                          static/**/*.html,\\\
                          static/js/tests/**,\\\
                          static/js/node_modules/**,\\\
                          main.go,\\\
                          scripts/**,\\\
                          playwright/**,\\\
                          static/js/api.js,\\\
                          static/js/app.js,\\\
                          static/js/drag.js,\\\
                          static/js/list-utils.js,\\\
                          static/js/vitest.config.js,\\\
                          static/js/components/card.js,\\\
                          static/js/login.js
