# Config file for running as Home Assistent Add-on
name: "wuFlow"
version: "0.22.2"
slug: "wuflow"
description: "Simple issue tracking app"
arch:
  - aarch64
  - amd64
image: ghcr.io/pwurbs/wuflow
startup: application
boot: auto
map:
  - type: share
    read_only: False
ports:
  8080/tcp: 5555
environment:
  WF_PORT: "8080"
  WF_DBPATH: "/share/wuflow/wuflow.db"
  WF_LOG_LEVEL: "info"
  WF_SECURE_COOKIE: "false"
